name: Publish

on:
  release:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish
      run: cargo publish --token ${CARGO_SECRET}
      env:
        CARGO_SECRET: ${{ secrets.CARGO_SECRET }}
